sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

script:
  - mvn clean package
  - docker build -t $DOCKER_REGISTRY/$DOCKER_NAMESPACE/coreapi-artifact .

after_success:
  - docker login --username $DOCKER_USER --password $DOCKER_PASSWORD $DOCKER_REGISTRY
  - docker push $DOCKER_REGISTRY/$DOCKER_NAMESPACE/coreapi-artifact
