version: '2'

services:
  artifactapi:
    build: .
    image: kickster/coreapi-artifact
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_ENABLED=false
    ports:
      - 8080