spring:
  profiles: docker
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
logging:
  level:
    com.auth0.spring.security: DEBUG