spring:
  profiles: docker
logging:
  level:
    root: WARN
    com:
      fasterxml:
        jackson: ERROR
      netflix:
        discovery: ERROR
      auth0:
        spring: ERROR
      google: ERROR
    org:
      springframework:
        security: DEBUG
        web: ERROR
      hibernate: ERROR
      trimou: DEBUG
      apache:
        http: ERROR