FROM {{languageValue}}:{{languageVersion}}
MAINTAINER {{capitalize organization}} Team

VOLUME /tmp
ADD target/{{architecture}}-{{namespace}}-1.0.0-SNAPSHOT.jar {{architecture}}-{{namespace}}.jar
RUN bash -c 'touch /{{architecture}}-{{namespace}}.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/{{architecture}}-{{namespace}}.jar"]